

-- Create User Threads table to manage conversation threads
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user_threads]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[user_threads] (
        [ThreadID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
        [UserEmail] NVARCHAR(255) NOT NULL,
        [ThreadTitle] NVARCHAR(500) NOT NULL, -- Generated by LLM
        [ThreadIcon] NVARCHAR(10) NULL, -- Generated by LLM (emoji)
        [IsActive] BIT NOT NULL DEFAULT 1,
        [TotalMessages] INT NOT NULL DEFAULT 0,
        [TotalTokens] INT NOT NULL DEFAULT 0,
        [LastActivityDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [ModifiedDate] DATETIME2 NOT NULL DEFAULT GETDATE()
    );
    
    PRINT 'User Threads table created successfully.';
END
ELSE
BEGIN
    PRINT 'User Threads table already exists.';
END


-- Create Thread Messages table to store individual messages in threads
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[thread_messages]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[thread_messages] (
        [MessageID] INT IDENTITY(1,1) PRIMARY KEY,
        [ThreadID] UNIQUEIDENTIFIER NOT NULL,
        [AgentID] INT NULL,
        [AgentName] NVARCHAR(100) NULL, -- Denormalized for performance
        [Role] NVARCHAR(20) NOT NULL, -- 'user', 'assistant', 'system'
        [Content] NVARCHAR(MAX) NOT NULL,
        [InputTokens] INT NOT NULL DEFAULT 0,
        [OutputTokens] INT NOT NULL DEFAULT 0,
        [TotalTokens] AS ([InputTokens] + [OutputTokens]) PERSISTED,
        [MessageOrder] INT NOT NULL, -- Order within thread
        [IsEdited] BIT NOT NULL DEFAULT 0,
        [EditedDate] DATETIME2 NULL,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [ModifiedDate] DATETIME2 NOT NULL DEFAULT GETDATE()
    );
    
    PRINT 'Thread Messages table created successfully.';
END
ELSE
BEGIN
    PRINT 'Thread Messages table already exists.';
END


-- Create User Session table to manage current user sessions and agent assignments
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user_current_session]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[user_current_session] (
        [SessionID] NVARCHAR(100) NOT NULL PRIMARY KEY, -- GUID string
        [UserEmail] NVARCHAR(255) NOT NULL UNIQUE, -- One active session per user
        [IsActive] BIT NOT NULL DEFAULT 1,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [ModifiedDate] DATETIME2 NOT NULL DEFAULT GETDATE()
    );
    
    PRINT 'User Current Session table created successfully.';
END
ELSE
BEGIN
    PRINT 'User Current Session table already exists.';
END


-- Create User Session Agents table to track agents registered in each session
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user_session_agents]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[user_session_agents] (
        [SessionAgentID] INT IDENTITY(1,1) PRIMARY KEY,
        [SessionID] NVARCHAR(100) NOT NULL,
        [AgentID] INT NOT NULL,
        [AgentName] NVARCHAR(100) NOT NULL, -- Denormalized for performance
        [AgentIcon] NVARCHAR(100) NULL, -- Denormalized for performance
        [IsActive] BIT NOT NULL DEFAULT 0, -- Only one can be active at a time per session
        [LaunchedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [ModifiedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        
        CONSTRAINT [UK_user_session_agents] UNIQUE ([SessionID], [AgentID])
    );
    
    PRINT 'User Session Agents table created successfully.';
END
ELSE
BEGIN
    PRINT 'User Session Agents table already exists.';
END


-- Create User Agent Usage Daily Summary table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user_agent_usage_daily]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[user_agent_usage_daily] (
        [UsageID] INT IDENTITY(1,1) PRIMARY KEY,
        [UserEmail] NVARCHAR(255) NOT NULL,
        [AgentID] INT NOT NULL,
        [AgentName] NVARCHAR(100) NOT NULL,
        [UsageDate] DATE NOT NULL,
        [TotalTokens] INT NOT NULL DEFAULT 0,
        [InputTokens] INT NOT NULL DEFAULT 0,
        [OutputTokens] INT NOT NULL DEFAULT 0,
        [MessageCount] INT NOT NULL DEFAULT 0,
        [ThreadCount] INT NOT NULL DEFAULT 0, -- Number of unique threads used
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [ModifiedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        
        CONSTRAINT [UK_user_agent_usage_daily] UNIQUE ([UserEmail], [AgentID], [UsageDate])
    );
    
    PRINT 'User Agent Usage Daily Summary table created successfully.';
END
ELSE
BEGIN
    PRINT 'User Agent Usage Daily Summary table already exists.';
END


-- Create User Agent Usage Monthly Summary table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user_agent_usage_monthly]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[user_agent_usage_monthly] (
        [UsageID] INT IDENTITY(1,1) PRIMARY KEY,
        [UserEmail] NVARCHAR(255) NOT NULL,
        [AgentID] INT NOT NULL,
        [AgentName] NVARCHAR(100) NOT NULL,
        [UsageMonth] NVARCHAR(7) NOT NULL, -- Format: YYYY-MM
        [TotalTokens] INT NOT NULL DEFAULT 0,
        [InputTokens] INT NOT NULL DEFAULT 0,
        [OutputTokens] INT NOT NULL DEFAULT 0,
        [MessageCount] INT NOT NULL DEFAULT 0,
        [ThreadCount] INT NOT NULL DEFAULT 0,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        [ModifiedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
        
        CONSTRAINT [UK_user_agent_usage_monthly] UNIQUE ([UserEmail], [AgentID], [UsageMonth])
    );
    
    PRINT 'User Agent Usage Monthly Summary table created successfully.';
END
ELSE
BEGIN
    PRINT 'User Agent Usage Monthly Summary table already exists.';
END


-- Create foreign key constraints
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_thread_messages_ThreadID]'))
BEGIN
    ALTER TABLE [dbo].[thread_messages]
    ADD CONSTRAINT [FK_thread_messages_ThreadID] FOREIGN KEY ([ThreadID])
    REFERENCES [dbo].[user_threads] ([ThreadID]) ON DELETE CASCADE;
    
    PRINT 'Foreign key constraint FK_thread_messages_ThreadID created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_thread_messages_AgentID]'))
BEGIN
    ALTER TABLE [dbo].[thread_messages]
    ADD CONSTRAINT [FK_thread_messages_AgentID] FOREIGN KEY ([AgentID])
    REFERENCES [dbo].[agents] ([AgentID]) ON DELETE CASCADE;
    
    PRINT 'Foreign key constraint FK_thread_messages_AgentID created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_user_agent_usage_daily_AgentID]'))
BEGIN
    ALTER TABLE [dbo].[user_agent_usage_daily]
    ADD CONSTRAINT [FK_user_agent_usage_daily_AgentID] FOREIGN KEY ([AgentID])
    REFERENCES [dbo].[agents] ([AgentID]) ON DELETE CASCADE;
    
    PRINT 'Foreign key constraint FK_user_agent_usage_daily_AgentID created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_user_agent_usage_monthly_AgentID]'))
BEGIN
    ALTER TABLE [dbo].[user_agent_usage_monthly]
    ADD CONSTRAINT [FK_user_agent_usage_monthly_AgentID] FOREIGN KEY ([AgentID])
    REFERENCES [dbo].[agents] ([AgentID]) ON DELETE CASCADE;
    
    PRINT 'Foreign key constraint FK_user_agent_usage_monthly_AgentID created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_user_session_agents_SessionID]'))
BEGIN
    ALTER TABLE [dbo].[user_session_agents]
    ADD CONSTRAINT [FK_user_session_agents_SessionID] FOREIGN KEY ([SessionID])
    REFERENCES [dbo].[user_current_session] ([SessionID]) ON DELETE CASCADE;
    
    PRINT 'Foreign key constraint FK_user_session_agents_SessionID created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_user_session_agents_AgentID]'))
BEGIN
    ALTER TABLE [dbo].[user_session_agents]
    ADD CONSTRAINT [FK_user_session_agents_AgentID] FOREIGN KEY ([AgentID])
    REFERENCES [dbo].[agents] ([AgentID]) ON DELETE CASCADE;
    
    PRINT 'Foreign key constraint FK_user_session_agents_AgentID created successfully.';
END


-- Create indexes for better performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_threads]') AND name = N'IX_user_threads_UserEmail')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_user_threads_UserEmail] ON [dbo].[user_threads] ([UserEmail]);
    PRINT 'Index on UserEmail for user_threads created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_threads]') AND name = N'IX_user_threads_LastActivityDate')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_user_threads_LastActivityDate] ON [dbo].[user_threads] ([LastActivityDate]);
    PRINT 'Index on LastActivityDate for user_threads created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[thread_messages]') AND name = N'IX_thread_messages_ThreadID_MessageOrder')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_thread_messages_ThreadID_MessageOrder] ON [dbo].[thread_messages] ([ThreadID], [MessageOrder]);
    PRINT 'Index on ThreadID and MessageOrder for thread_messages created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[thread_messages]') AND name = N'IX_thread_messages_AgentID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_thread_messages_AgentID] ON [dbo].[thread_messages] ([AgentID]);
    PRINT 'Index on AgentID for thread_messages created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[thread_messages]') AND name = N'IX_thread_messages_CreatedDate')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_thread_messages_CreatedDate] ON [dbo].[thread_messages] ([CreatedDate]);
    PRINT 'Index on CreatedDate for thread_messages created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_current_session]') AND name = N'IX_user_current_session_UserEmail')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [IX_user_current_session_UserEmail] ON [dbo].[user_current_session] ([UserEmail]);
    PRINT 'Unique index on UserEmail for user_current_session created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_agent_usage_daily]') AND name = N'IX_user_agent_usage_daily_UserEmail_Date')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_user_agent_usage_daily_UserEmail_Date] ON [dbo].[user_agent_usage_daily] ([UserEmail], [UsageDate]);
    PRINT 'Index on UserEmail and UsageDate for user_agent_usage_daily created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_agent_usage_monthly]') AND name = N'IX_user_agent_usage_monthly_UserEmail_Month')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_user_agent_usage_monthly_UserEmail_Month] ON [dbo].[user_agent_usage_monthly] ([UserEmail], [UsageMonth]);
    PRINT 'Index on UserEmail and UsageMonth for user_agent_usage_monthly created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_session_agents]') AND name = N'IX_user_session_agents_SessionID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_user_session_agents_SessionID] ON [dbo].[user_session_agents] ([SessionID]);
    PRINT 'Index on SessionID for user_session_agents created successfully.';
END


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[user_session_agents]') AND name = N'IX_user_session_agents_AgentID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_user_session_agents_AgentID] ON [dbo].[user_session_agents] ([AgentID]);
    PRINT 'Index on AgentID for user_session_agents created successfully.';
END


-- Display summary of thread management tables
SELECT 
    COUNT(*) as TotalThreads
FROM [dbo].[user_threads];

SELECT 
    COUNT(*) as TotalMessages
FROM [dbo].[thread_messages];

SELECT 
    COUNT(*) as TotalActiveSessions
FROM [dbo].[user_current_session]
WHERE [IsActive] = 1;

SELECT 
    COUNT(*) as TotalSessionAgents
FROM [dbo].[user_session_agents]
WHERE [IsActive] = 1;



PRINT 'Thread Management System initialized successfully!';

